version: 2.1

parameters:
  manual:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "aaakka"

workflows:
  build-image:
    when: 
      or:
        - << pipeline.parameters.manual >>
        - equal:  [ api, << pipeline.trigger_source >> ]
    jobs:
      - build
