version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    step:
      - checkout
      - run: echo "aaaa"

workflows:
  jobs:
    when:
      equal: [ api, << pipeline.trigger_source >> ]
    - build
