version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    step:
      - checkout
      - run: echo "aaaa"

workflows:
  build-image:
    when:
      equal: [ api, << pipeline.trigger_source >> ]
    jobs:
      - build
  version: 2
