version: 2.1
jobs:
  parameters:
    run-manual:
      type: boolean
      default: false
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "aaakka"

workflows:
  build-image:
    when:
      equal: [ api, << pipeline.trigger_source >> ]
    when: << pipeline.parameters.manual >>
    jobs:
      - build
  version: 2
