version: 2.1
jobs:
  parameters:
    manual:
      type: string
      default: ""
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "aaaa"

workflows:
  build-image:
    when:
      equal: [ api, << pipeline.trigger_source >> ]
      equal: [ true, << pipeline.parameters.manual >> ]
    jobs:
      - build
  version: 2
